### ISSUE TITLE
Invalid menu item in easymenu

### ISSUE THREAD

**Issue by terryzhouke** [mmarshall540/mini-config#1]
Debugger entered--Lisp error: (error "Invalid menu item in easymenu")
  error("Invalid menu item in easymenu")

**Comment by mmarshall540** [comment]
Hi, and thank you for the bug report!

~~Is this happening on startup, or later, after you enter some particular major mode or enable some particular minor mode?~~

~~Which version of Emacs are you running?~~

Ah, I see it now.  Didn't notice it before as it's specific to version 28.

Hopefully the latest commit fixes it for you too.  If not, please let me know!

Best regards.

**Comment by mmarshall540** [comment]
Closing, as this should now be resolved by 0ceba40.

Thanks again for the bug report.
